# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'ChoreSolver' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChoreSolver
  pod ‘Bond’, ‘4.0.0’
  pod “ConvenienceKit”
  pod ‘Parse’
  pod ‘ParseFacebookUtilsV4’
  pod ‘ParseUI’
  pod ‘DropDown’
  pod 'IHKeyboardAvoiding'
  pod ‘FlatUIKit’
  pod ‘OneSignal’
  pod ‘Cosmos’, ‘~> 1.2’
  pod 'Atlas'
  pod 'SVProgressHUD'
end
